### ISSUE TITLE
is it possible  to make it  work with even faster Movenet models?

### ISSUE THREAD

**Issue by JackJagt** [0x48lab/flutter_body_detection#1]
Like 
https://tfhub.dev/google/movenet/singlepose/lightning/4

**Comment by 0x48Maciek** [comment]
Possibly, but as this would require TensorFlow Lite integration it might be a better idea to have a separate flutter plugin so as not to multiply dependencies and keep things focused.

**Comment by JackJagt** [comment]
You are right i asked because i want to run it on a low end tablet

**Comment by JackJagt** [comment]
Is it possible to upgrade it to use the latest beta and the base sdk?
dependencies {
  // If you want to use the base sdk
  implementation 'com.google.mlkit:pose-detection:17.0.1-beta7'
  // If you want to use the accurate sdk
  implementation 'com.google.mlkit:pose-detection-accurate:17.0.1-beta7'
}

**Comment by 0x48Maciek** [comment]
Thanks for pointing out old dependencies, I'll add updating them to our backlog.

As for the usage of the base SDK, I could add a parameter to the library's API calls to choose accuracy.
One thing that needs to be considered though, is that according to https://developers.google.com/ml-kit/vision/pose-detection/android this will increase app size by ~11MB (code and assets are linked statically, so that will also impact the size of the apps that don't use it).

As for your case of running it on a low-end tablet, it might be worth looking into decreasing the size of the image fed into MLKit pose detector.

Are you using single-image detection or live camera feed one?

We now feed the image acquired from the camera directly, but could potentially enable resizing the image beforehand under an option. That would bring us new things to consider like whether to let library users set custom size, only scale, or some size presets; whether to make it aspect ratio dependent etc.

Using raw image mask in selfie segmentation worked wonders for performance on a few years old tablet, though the computations are obviously different for pose detection. It would be a good thing to have some data on whether reducing image size could help in your case. You could try using exponentially lower image sizes (each time divide the size by two) and time the call to API's `detectImagePose` (while checking that you still get passable detection results) which could give you some rough estimate.

**Comment by JackJagt** [comment]
Thank you fore your extensive answer.
In relation to the base or accurate SDK  i was thinking about choosing by commenting one out and build again by myself 
But im afraid that it needs extra work than just replacing it with the base SDK

**Comment by JackJagt** [comment]
I still have a question the posedetection works on a life camerastream but want it also run on legancy hardware like:

Model:Archos Hello 5
Manufacturer:Archos
Build:8.1.0
SDK:27
------------------------------------------
Camera ID: 0
Camera Facing: BACK
Hardware Support Level:LEGACY
Manual exposure:0
Auto exposure:1
Auto exposure, always flash:0
Auto exposure, auto flash:0
Auto exposure, auto flash, red eye reduction:0

**Comment by 0x48Maciek** [comment]
I've pushed the `performance` branch with the following changes:
- changed pose detection library used from accurate to base,
- update dependencies versions (pose detection to latest 18.0.0-beta1),
- changed preferred camera image size for analysis to 320x240.

This should boost performance on low end devices. You can see changes in the latest commit (1a41d7ed) and modify to suit your needs.
Mind you, the docs at https://developers.google.com/ml-kit/vision/pose-detection/android state that:

> For ML Kit to accurately detect pose, the person in the image should be represented by sufficient pixel data; for best performance, the subject should be at least 256x256 pixels.

320x240 might be a bit low, but you can try with that or other values and see what works for you.

I don't think flutter allows for plugins to have different flavors, so to use this you should clone this repo, put somewhere under your project (maybe under plugins directory) and reference from pubspec.yaml like the example app does, something like:
```
dependencies:
  body_detection:
    path: ./plugins/body_detection
```

Hope this helps.

**Comment by JackJagt** [comment]
It helps thank  you very much
